import sys

from PyQt4 import QtGui, QtCore

from qq import Ui_self


class MainWindow(QtGui.QMainWindow):
    def __init__(self):
        QtGui.QMainWindow.__init__(self)
        self.setObjectName("MainWindow")
        self.resize(798, 499)
        self.centralwidget = QtGui.QWidget(self)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 300))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(4)
        self.splitter.setObjectName("splitter")
        self.widget_2 = QtGui.QWidget(self.splitter)
        self.widget_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget_2.setObjectName("widget_2")
        # self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        # self.horizontalLayout_2.setMargin(0)
        # self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # self.listWidget = QtGui.QListWidget(self.widget_2)
        # self.listWidget.setStyleSheet("border:none")
        # self.listWidget.setObjectName("listWidget")
        # self.horizontalLayout_2.addWidget(self.listWidget)
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        # self.splitter_2 = QtGui.QSplitter(self.widget)
        # self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        # self.splitter_2.setHandleWidth(3)
        # self.splitter_2.setObjectName("splitter_2")
        # self.widget_3 = QtGui.QWidget(self.splitter_2)
        # self.widget_3.setMinimumSize(QtCore.QSize(0, 300))
        # self.widget_3.setObjectName("widget_3")
        # self.formLayout = QtGui.QFormLayout(self.widget_3)
        # self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        # self.formLayout.setObjectName("formLayout")
        # self.pushButton = QtGui.QPushButton(self.widget_3)
        # self.pushButton.setObjectName("pushButton")
        # self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushButton)
        # self.pushButton_2 = QtGui.QPushButton(self.widget_3)
        # self.pushButton_2.setObjectName("pushButton_2")
        # self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_2)
        # self.pushButton_3 = QtGui.QPushButton(self.widget_3)
        # self.pushButton_3.setObjectName("pushButton_3")
        # self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_3)
        # self.textBrowser = QtGui.QTextBrowser(self.splitter_2)
        # self.textBrowser.setBaseSize(QtCore.QSize(0, 50))
        # self.textBrowser.setObjectName("textBrowser")
        # self.verticalLayout_4.addWidget(self.splitter_2)
        self.lineEdit = QtGui.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        # self.horizontalLayout.addWidget(self.splitter)
        # self.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 23))
        self.menubar.setObjectName("menubar")
        self.menuConnections = QtGui.QMenu(self.menubar)
        self.menuConnections.setObjectName("menuConnections")
        self.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(self)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        self.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(self)
        self.actionNew.setObjectName("actionNew")
        self.actionNew.triggered.connect(self.__show_conn_window)
        self.actionConnection = QtGui.QAction(self)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/png/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnection.setIcon(icon)
        self.actionConnection.setObjectName("actionConnection")
        self.menuConnections.addAction(self.actionNew)
        self.menubar.addAction(self.menuConnections.menuAction())
        self.toolBar.addAction(self.actionConnection)

        self.setWindowTitle("MainWindow")
        # self.pushButton.setText("MainWindow")
        # self.pushButton_2.setText("MainWindow")
        # self.pushButton_3.setText("MainWindow")
        self.menuConnections.setTitle("MainWindow")
        self.toolBar.setWindowTitle("MainWindow")
        self.actionNew.setText("MainWindow")
        self.actionConnection.setText("MainWindow")


    def __show_conn_window(self):
        dialog = QtGui.QDialog()
        dialog.resize(300, 200)
        hostname = QtGui.QLineEdit(dialog)
        hostname.move(10, 10)
        dialog.exec_()


if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    mainWindow = MainWindow()
    mainWindow.show()
    #
    sys.exit(app.exec_())